# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.7
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: 93330009+xxiled-plastic-cat@users.noreply.github.com
author_name: Xxiled
contract_name: staking
preset_name: starter
project_name: contracts

